### ISSUE TITLE
show option how many times you want to attack

### ISSUE THREAD

**Issue by adhavalboy** [adhavalboy/node-email-attacker#1]
if user enter 5 times then it should send five times

**Comment by ankush4144** [comment]
can you please elaborate the issue??

**Comment by barthclem** [comment]
@ankush4144 , I think he is referring to the number of times that the for loop in the code should run

**Comment by jacquesdev** [comment]
Who are you planning on attacking :)

**Comment by adhavalboy** [comment]
@ankush4144 yes
